/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Client;
import java.util.List;

/**
 *
 * @author Família
 */
public class ViewAll extends javax.swing.JFrame {

    private JTable clientsTable;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ViewAll
     */
    public ViewAll() {
        initComponents(); // Inicializa os componentes criados pelo NetBeans
        initializeTable(); // Chama o método para inicializar a tabela
    }

    private void initializeTable() {
        // Inicializa o TableModel com as colunas desejadas
        tableModel = new DefaultTableModel(
                new Object[]{"CPF", "Nome", "Email", "Telefone", "Endereço", "Data de Nascimento"}, 0);
        clientsTable = new JTable(tableModel); // Atribui o tableModel ao jTable1
        jTable1.setModel(tableModel); // Garante que o jTable1 use o nosso TableModel
        jScrollPane1.setViewportView(jTable1); // Garante que a tabela está dentro do ScrollPane
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View All");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public void populateTable(List<Client> clients) {
        // Limpar a tabela antes de adicionar novos dados
        tableModel.setRowCount(0);

        // Adicionar cada cliente à tabela
        for (Client client : clients) {
            tableModel.addRow(new Object[]{
                client.getCpf(),
                client.getName(),
                client.getEmail(),
                client.getPhone(),
                client.getAddress(),
                client.getBirthdate()
            });
        }
        // Notificar a tabela que os dados foram alterados
        tableModel.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
